# Vault-FAQs

## Frequently Asked Questions (FAQs)

<table data-full-width="true"><thead><tr><th width="98">Priority</th><th width="105">Module</th><th>Error</th><th>Debug Steps</th><th>Cause</th><th>Resolution</th><th>Addl Resources</th></tr></thead><tbody><tr><td>1</td><td>Restore/Replicate</td><td>CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>This error is a result of an issue stemming from a trigger in the Org.</td><td>Use the option to disable the triggers in the job configuration. For the triggers which cannot be disabled via metadata API, manually disable the triggers in the Salesforce and re-run the job.</td><td> </td></tr><tr><td>2</td><td>Restore/Replicate</td><td>CANNOT_EXECUTE_FLOW_TRIGGER:We can't save this record because the ‘Online Applicant Validation’ process failed. Give your Salesforce admin these details. An error occurred when executing a flow interview.<br> Error ID: 1545064308-45750 (1670083917):--</td><td>Click on Replicate/restore job summary-> Click on Failure records-> view error in 'Error' column</td><td>This error typically indicates that there is a Process Builder process / Flow in place which is causing the upsert operation to fail.</td><td><p>Locate the process builder process / flow that caused the error. Temporarily disable the automation and rerun the job to restore/replicate failed records.</p><p>Alternately, the job can be retried by specifying a lower batch size in the job config which prevents the process builders/flows from hitting the parallel processing limits in Salesforce.</p></td><td> </td></tr><tr><td>3</td><td>Restore/Replicate</td><td>INACTIVE_OWNER_OR_USER</td><td>Click on Replicate/Restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>This error is due to the owner of the records about to be inserted into the destination org is inactive in the destination org.</td><td>Enable "Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners"  permissions in Salesforce settings and also enable these permissions in the permission set corresponding to the data loading user in the destination org. Refer to the link in the additional resources column for the details on how to do it in Salesforce.</td><td><a href="https://help.salesforce.com/articleView?id=000334870&#x26;type=1&#x26;mode=1">https://help.salesforce.com/articleView?id=000334870&#x26;type=1&#x26;mode=1</a></td></tr><tr><td>4</td><td>Restore/Replicate</td><td>FIELD_CUSTOM_VALIDATION_EXCEPTION</td><td>Click on Restore/Replicate job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>This error is due to validation rules applied on certain fields.</td><td>Disable validation rules in the restore modal in the final step of the restore process.</td><td> </td></tr><tr><td>5</td><td>Restore/Replicate</td><td>INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Such failures occur when the destination org doesn't have the value enabled that is selected in the source org.</td><td><p>Sync the values in the restricted picklist between the source and destination.</p><p>Alternately, use the mappings for restricted picklist to cross-map a value in the restricted picklist from source to another value in the destination org as part of the replicate job config.</p></td><td> </td></tr><tr><td>6</td><td>Restore/Replicate</td><td>REQUIRED_FIELD_MISSING</td><td>Click on Replicate/Restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Such errors occur when failure of a required parent record(related through master-detail/required lookup) leads to the failure of its associated child records.</td><td>Check the fields that failed. Review the error corresponding to the failure of the referencing parent record(s), rectify them, and restore the corresponding failed parent records first, then restore failed related child records.</td><td> </td></tr><tr><td>7</td><td>Replicate</td><td>DUPLICATE_VALUE</td><td>Click on Replicate job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Such failures occurs when such records are already present in the destination</td><td>An existing automation is blocking the upsert operation. Try disabling the automation if necessary.<br><br>If you would like Vault to recognize the existing records in the destination that are created/transferred outside of Vault, you can configure unique identifier for the object and enable the option ‘Prevent duplicate record creation using unique identifers’ in replicate job config to avoid Vault from attempting to recreate an existing record matching the value in the unique identifier specified. For steps on how to configure unique identifiers, please go through the link specified in the ‘additional resources’ column.</td><td><a href="https://knowledgebase.autorabit.com/product-guides/vault/configuring-vault/registering-salesforce-org/unique-identifier-uid"><img src="https://1912836914-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F9vAxMuDrkUkB4OXlH9CL%2Ficon%2F5XjNxbGvclugTa6yLCYO%2FAutorabit-Logo-Light%402x-1%20copy.png?alt=media&#x26;token=35ad9bb5-be66-429f-bc46-7b9826822d21" alt="">Unique Identifier (UID) | AutoRABIT Knowledge Base</a></td></tr><tr><td>8</td><td>Restore/Replicate</td><td>INVALID_CROSS_REFERENCE_KEY</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>The Parent record is not included in the job or permission issue(s) on the parent object or a lookup relationship is not included in the job</td><td><ol start="1"><li>Verify the parent object is included in the job.</li><li>Review the authenticated user has access to the parent record that is referenced within the error.</li><li>If it is a lookup relationship ensure the parent object is included in the job</li></ol></td><td> </td></tr><tr><td>9</td><td>Restore/Replicate</td><td>CANNOT_UPDATE_CONVERTED_LEAD</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>A Lead record once converted (to a contact) becomes read only. You cannot update such leads.</td><td>You can check if the lead is converted by checking the isConverted field.</td><td> </td></tr><tr><td>10</td><td>Restore/Replicate</td><td>FIELD_INTEGRITY_EXCEPTION</td><td>Click on Replicate/restore job summary-> Click on Failure records-> view error in 'Error' column</td><td>This error mostly occurs when upsert tried to populate a lookup field with a wrong ID either because the parent got failed or Vault is unable to recognize the parent record Id.</td><td>Need to pass the correct Id for a lookup field</td><td> </td></tr><tr><td>11</td><td>Restore/Replicate</td><td>Metadata deployment error...com.sforce.ws.SoapFaultException: INVALID_OPERATION: Too many files in zip</td><td>Click on Replicate/restore job summary-> Click on logs->  view error the 'Error' </td><td>More than 10,000 files are there in the .zip file. It violates a governor limit</td><td>Reduce the number of metadata components restored/replicated in each job.</td><td> </td></tr><tr><td>12</td><td>Restore/Replicate</td><td>Record Type access issue</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Salesforce user authenticated on Vault doesn’t have access to some record types of an object(s)</td><td>Give appropriate access using profiles and permissions to the Salesforce user authenticated on Vault</td><td> </td></tr><tr><td>13</td><td>Restore/Replicate</td><td>Unknown user permission </td><td>Click on Replicate/restore job summary-> Click on Failure records-> view error in 'Error' column</td><td>Required user permissions are missing in Salesforce.</td><td>Assign user to the desired permission set in Salesforce</td><td> </td></tr><tr><td>14</td><td>Restore/Replicate</td><td>INVALID_CROSS_REFERENCE_KEY:Record Type ID: this ID value isn't valid for the user: 012D0000000BfaLIAS:RecordTypeId --</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Salesforce user authenticated on Vault doesn’t have access to some record types of an object(s)</td><td>Give appropriate access using profiles and permissions to the Salesforce user authenticated on Vault</td><td> </td></tr><tr><td>15</td><td>Restore/Replicate</td><td>CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:SFSSDupeCatcher.SSDupeCatcherContactTrigger: System.LimitException: Apex CPU time limit exceeded:--</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Triggers are preventing the records from getting loaded in the destination org</td><td>Disable the triggers on the destination org either by using the option to disable triggers in Vault or by performing the same in Salesforce org.<br><br>Alternately, try lowering the batch size of the operation to avoid more records from getting inserted/updated in parallel resulting the CPU time limit exception.</td><td> </td></tr><tr><td>16</td><td>Restore/Replicate</td><td>UNABLE_TO_LOCK_ROW:unable to obtain exclusive access to this record or 126 records</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Dependent records causing the load of records from populating in the destination org.</td><td>Execute the job in serial mode instead of parallel mode to help prevent records in different batches having dependency with each other getting inserted to salesforce in parallel resulting in the error.</td><td> </td></tr><tr><td>17</td><td>Restore/Replicate</td><td>TooManyLockFailure : Too many lock failure 200 Trying again later.;</td><td>Click on Replicate/restore job summary-> Click on Failure records-> download details-> view error in 'Error' column</td><td>Dependent records causing the load of records from populating in the destination org.</td><td>Decrease the batch size or execute the job in serial mode instead of parallel mode to help prevent records in different batches having dependency with each other getting inserted to salesforce in parallel resulting in the error.</td><td><a href="https://developer.salesforce.com/forums/?id=906F0000000D9CuIAK"><img src="https://trailhead.salesforce.com/community/favicon-16x16.png" alt="">Feed Item Detail | Salesforce Trailblazer Community</a></td></tr></tbody></table>
